name: Waka Readme Stats

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # Required secrets
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # --- New, Valid Options ---
          # Use the options below to customize your stats block
          
          SHOW_TOTAL_CODE_TIME: true  # This option was already correct
          SHOW_LANGUAGE: true         # To display a list of languages you use
          SHOW_DAYS_OF_WEEK: true     # Shows a bar chart of your activity by day
          SHOW_OS: true               # Shows which Operating Systems you code on
          SHOW_EDITORS: true          # Shows which Code Editors you use
          # SHOW_PROJECTS: true         # Uncomment this line if you want to show project stats