name: Waka Readme Stats

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest

    # Explicitly setting write permissions for this job
    permissions:
      contents: write

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # It's still recommended to use the PAT for authentication
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
          # Your chosen options
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LANGUAGE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_OS: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true